site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotatevscode

nav:
  - Welcome to MkDocs: index.md
  - Tutorials:
    - Golang DevContainer: tutorials/go-setup.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences